"""Use a human recording as the narration instead of TTS.

  python3 tools/voice_from_recording.py out/rec/narration.m4a

Needs out/rec/alignment.json (tools/align_recording.py). Cleans the voice (noise reduction, high-pass, gentle
de-essing and compression, soft gate between phrases), keeps the speaker's own pacing, and writes
out/voice.wav plus src/timing.js (same format as tools/tts.py, so the scenes follow the new rhythm).
"""
import json, os, subprocess, sys
import numpy as np, soundfile as sf

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REC = sys.argv[1]
CLEAN = '--clean' in sys.argv          # studio/TTS source: no denoise or gate, just tone and level
SR, FPS, FIRST_LEAD, LAST_TAIL = 48000, 25, 3.2, 9.0
script = json.load(open(os.path.join(ROOT, 'script.json'), encoding='utf-8'))
A = json.load(open(os.path.join(ROOT, 'out/rec/alignment.json'), encoding='utf-8'))['lines']

FX = ','.join([
    'highpass=f=75', 'afftdn=nr=14:nf=-50:tn=1',                   # rumble + steady background noise
    'equalizer=f=180:t=q:w=1:g=1.5', 'equalizer=f=3000:t=q:w=1.2:g=1.5',   # body + presence
    'deesser=i=0.5', 'acompressor=threshold=-24dB:ratio=3:attack=8:release=180:makeup=4',
    'agate=threshold=0.012:ratio=2.5:attack=15:release=350:range=0.25',    # softens room noise between phrases
    'alimiter=limit=0.89'])
if CLEAN: FX = 'highpass=f=60,equalizer=f=200:t=q:w=1:g=1,acompressor=threshold=-26dB:ratio=2:attack=10:release=200:makeup=6,alimiter=limit=0.89'
p = subprocess.run(['ffmpeg', '-v', 'error', '-i', REC, '-ac', '1', '-ar', str(SR), '-af', FX, '-f', 'f32le', '-'], capture_output=True, check=True)
rec = np.frombuffer(p.stdout, np.float32).copy()

shift = FIRST_LEAD - A[0]['start']                                    # recording time + shift = video time
voice = np.concatenate([np.zeros(max(0, int(shift * SR)), np.float32), rec[max(0, int(-shift * SR)):]])
last_end = A[-1]['end'] + shift
dur = last_end + LAST_TAIL
n = int(np.ceil(dur * SR)); voice = np.pad(voice, (0, max(0, n - len(voice))))[:n]
# fade out anything after the last word (room tone, the click of the stop button)
tail0 = int((last_end + .4) * SR); voice[tail0:] *= np.exp(-np.arange(n - tail0) / (.25 * SR)).astype(np.float32)
voice *= .89 / np.max(np.abs(voice))

timeline, li = [], 0
for si, sc in enumerate(script['scenes']):
    lines = []
    for ln in sc['lines']:
        a = A[li]; li += 1
        lines.append({'start': round(a['start'] + shift, 3), 'end': round(a['end'] + shift, 3), 't': ln['t']})
    timeline.append({'id': sc['id'], 'title': sc['title'], 'lines': lines})
for si, sc in enumerate(timeline):
    first = sc['lines'][0]['start']
    if si == 0: sc['start'] = 0.0
    else:
        prev = timeline[si - 1]['lines'][-1]['end']
        sc['start'] = round(min(first - .6, (prev + first) / 2), 3)
for si, sc in enumerate(timeline):
    sc['end'] = timeline[si + 1]['start'] if si + 1 < len(timeline) else round(dur, 3)
timeline = [{'id': s['id'], 'title': s['title'], 'start': s['start'], 'end': s['end'], 'lines': s['lines']} for s in timeline]

hop = SR // FPS; nf = int(np.ceil(dur * FPS))
env = np.array([np.sqrt(np.mean(voice[i * hop:(i + 1) * hop] ** 2)) if i * hop < n else 0 for i in range(nf)])
env = np.clip(env / (np.percentile(env[env > .01], 90) + 1e-6), 0, 1)
env[env < .08] = 0                                                   # don't flap the mouth on room noise
env = np.convolve(env, [.25, .5, .25], mode='same')

sf.write(os.path.join(ROOT, 'out/voice.wav'), voice, SR)
with open(os.path.join(ROOT, 'src/timing.js'), 'w', encoding='utf-8') as f:
    f.write('// generated by tools/voice_from_recording.py — do not edit\nwindow.TIMING = ' +
            json.dumps({'fps': FPS, 'duration': round(dur, 3), 'scenes': timeline, 'env': [round(float(x), 2) for x in env]}, ensure_ascii=False) + ';\n')
print(f'duration {dur:.1f}s ({dur / 60:.1f} min)')
for s in timeline: print(f"  {s['id']:12s} {s['start']:7.1f} → {s['end']:7.1f}  ({s['end'] - s['start']:.1f}s)")
